#
# Global config
#
protocol-group ff02:0:0:0:0:0:1:6
protocol-port 6696
kernel-priority 1
reflect-kernel-metric false
random-id false
local-path-readwrite /var/run/babel.sock
protocol-buffer-size 65536
#
# Routing tables:
#  20: General 10.X routes (IN)
#  21: Routes to supernode (IN), or supernode's blackholes (OUT)
#  22: Default WAN route important (IN)
#  28: Default WAN route for this gateway (OUT)
#  29: Local LAN routes (OUT)
#
export-table 20
import-table 28
import-table 29
link-detect false
daemonise false
state-file /etc/state/babel-state
shutdown-delay-ms 5000
log-file /dev/stdout
pid-file /var/run/babeld.pid
#
# Default interface setup.
# Other defaults are extracted from babel uci.
#
default type auto
default link-quality true
default split-horizon false
default enable-timestamps true
default unicast false
default link-quality true
default rfc6126-compatible false
default v4-via-v6 false
default probe-mtu false
