#!/bin/sh /etc/rc.common

USE_PROCD=1
START=97
STOP=20

start_service() {
    procd_open_instance babel
    procd_set_param command /usr/sbin/babeld_wrapper -c /etc/babel.conf
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root
    procd_close_instance
}

stop_service() {
    kill -1 $(cat /var/run/babeld.pid)
}

restart() {
    stop
    sleep 5
    start
}
