#
# Global config
#
protocol-group ff02:0:0:0:0:0:1:6
protocol-port 6696
reflect-kernel-metric false
random-id false
local-path-readwrite /var/run/babel.sock
export-table 20
import-table 29
import-table 254
link-detect true
daemonise false
state-file /etc/state/babel-state
log-file /dev/stdout
pid-file /var/run/babeld.pid
#
# Default interface setup
#
default type auto
default link-quality false
default split-horizon false
default rxcost 96
default hello-interval 4
default update-interval 16
default enable-timestamps false
default unicast false
default rfc6126-compatible false
default rtt-decay 42
default rtt-min 10
default rtt-max 120
default v4-via-v6 false
default probe-mtu false
