#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2010 OpenWrt.org
START=50

has_root_pwd() {
	local pwd=$([ -f "$1" ] && cat "$1")
	      pwd="${pwd#*root:}"
	      pwd="${pwd%%:*}"

	test -n "${pwd#!}"
}

start() {
		telnetd -l /bin/login.sh
}

stop() {
	killall telnetd 2>/dev/null
}

